Update docs.yml

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -28,7 +28,29 @@ jobs:
         doxyfile-path: "./dconfig" # default is ./Doxyfile
         # Working directory
         working-directory: "." # default is .
+    - name: Build latex
+      run: |
+        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk
+        ls -la 
+        ls -la docs
+        cd docs/
+        
+        mkdir -p latex-build
+        cp -r latex/* latex-build/
+        cd latex-build
 
+        # Build the PDF
+        latexmk -pdf -interaction=nonstopmode refman.tex || {
+          echo "❌ LaTeX PDF build failed"
+          exit 1
+        }
+
+        # Move the generated PDF back to the main directory
+        cp refman.pdf ../docs/documentation.pdf
+        cd ..
+
+        
+        
     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
@@ -37,13 +59,6 @@ jobs:
         # Change the directory if changes in Doxyfile
         publish_dir: ./docs/
 
-    - name: Build latex
-      run: |
-        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk
-        ls -la 
-        ls -la docs
-        cd docs/latex 
-        make
-        
+   
     
    
